config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users
  resources :requests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  enum status: { "新規": 0,"対応中":1,"完了":2 }

  def self.title_search(search) #self.でクラスメソッドとしている
      Request.where(['title LIKE ?', "%#{search}%"]) 
  end
  
  def self.status_search(search) #self.でクラスメソッドとしている
      Request.where(['status = ?', search])
  end


  #リクエスｔの担当者を返す
  def charge_user_name
    if self.charge_user.nil?
      return self.charge_user.to_s
    else
      charge_user = User.find(self.charge_user)
      return charge_user.name
    end
  end


  belongs_to :user
  # belongs_to :charge_user, class_name: 'User' ,primary_key: 'charge_user'

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :message, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { "一般": 0,"管理者":1 }

  #ADMIN権限かどうか？
  def admin?
    self.role == "管理者"
  end

  #ユーザー名による絞り込み 
  scope :get_by_name, ->(name) {
  where("name like ?", "%#{name}%")
  }

  #権限による絞り込み
  scope :get_by_role, ->(role) {
  where(role: role)
  }


   # validationの設定
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  # パスワード暗号化
  has_secure_password
  
  has_many :requests, foreign_key: 'user'
  # has_many :requests, foreign_key: 'charge_user'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :require_user_logged_in
  require 'date'
  
  def index
    # 対応済以外を渡す
    @requests = Request.find_by_sql("select * from requests where status < 2 order by created_at desc")

    @requests = Request.title_search(params[:title]) if params[:title].present? 
    @requests = Request.status_search(params[:status]) if params[:status].present?

  end

  def show
    @request = Request.find(params[:id])
    @user = User.find(@request.user)
  end

  def new
    @request = Request.new(user_id: current_user.id,limit_date: Date.today+7,status: 0)
  end

  def update
    @request = Request.find(params[:id])
    @request.charge_user = params[:charge_user_id] if params[:charge_user_id]
    @request.status = params[:status] if params[:status]

    if params[:charge_user_id] && @request.save
      flash[:success] = 'request は正常に更新されました'
       redirect_back(fallback_location: root_url)
    elsif @request.update(request_params)
      flash[:success] = 'request は正常に更新されました'
      redirect_to @request
    else
      flash.now[:danger] = 'request は更新されませんでした'
      render :edit
    end
  end

  def edit
    @request = Request.find(params[:id])
    @user = User.find(@request.user)
  end

  def create
    # @request = Request.new(request_params)

  @request = current_user.requests.build(request_params)

    if @request.save
      flash[:success] = 'メッセージを投稿しました。'
      # redirect_to @request
      redirect_to root_path
    else
      @requests = current_user.requests.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      render :new
    end    
    
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    flash[:success] = 'request は正常に削除されました'
    redirect_to root_url

  end

  private

  # Strong Parameter
  def request_params
    params.require(:request).permit(:title,:limit_date,:description,:status,:charge_user,:message)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url    
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end  
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      @request = current_user.requests.build  # form_for 用
      @requests = current_user.requests.order('created_at DESC').page(params[:page])
      @tasks = Request.where("charge_user = ? and status < 2" ,current_user.id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    # パラメータとして名前か性別を受け取っている場合は絞って検索する
    @users = @users.get_by_name params[:name] if params[:name].present? 
    @users = @users.get_by_role params[:role] if params[:role].present?
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = 'user は正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = 'user は更新されませんでした'
      render :edit
    end

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    flash[:success] = 'ユーザは正常に削除されました'
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :dept, :base, :role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2018 IT-IRAI.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-left" href="/"><img src="/images/logo.png" alt="it-irai"></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>

            <!--依頼一覧は管理者の場合のみ表示される-->
              <li><%= link_to '依頼一覧', requests_path if current_user.admin? %></li>


            <!--ユーザ一覧は管理者の場合のみ表示される-->
            <% if current_user.admin? %>
              <li><%= link_to 'ユーザ一覧', users_path %></li>
            <% end %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My profile', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
          <li><%= link_to 'ユーザ登録', signup_path %></li>
          <li><%= link_to 'ログイン', login_path %></li>
        <% end %>
      </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>IT依頼</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield :cover %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/requests/_form.html.erb
  <div class="row">
    <%= form_for(@request) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
  
      <div class="form-group">
        <%= label :limit_date, '依頼者' %>
        <%= text_field_tag "user_name",current_user.name ,:readonly => true, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :limit_date, '期日' %>
        <%= f.text_field :limit_date,  class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :description, '内容' %>
        <%= f.text_area :description, class: 'form-control', rows: 10 %>
      </div>
  
      <% if @request.persisted? %>
    
          <div class="form-group">
            <%= f.label :message, '回答内容' %>
            
            <% if current_user.admin? %>
              <%= f.text_area :message, class: 'form-control', rows: 10 %>
            <% else %>
              <%= f.text_area :message,:readonly => true, class: 'form-control', rows: 10 %>
            <% end %>
    
          </div>

          <div class="form-group">
            <%= f.label :status, '状況' %>
            <% if current_user.admin? %>
              <%= f.select :status, Request.statuses.keys.to_a, {},  class: 'form-control',:style => "width:140px" %>
            <% else %>
              <%= f.text_field :status, :readonly => true, :style => "width:140px", class: 'form-control' %>
            <% end %>
          </div>
  
          <div class="form-group">
            <%= f.label :charge_user, '' %>
            <%= f.text_field :charge_user_name,:readonly => true, class: 'form-control' %>
          </div>
  
  
      <% else %>  
        <%= f.hidden_field :status, :value => "新規" %>
        <%= f.hidden_field :message, :value => '' %>
        <%= f.hidden_field :charge_user, :value => '' %>
      <% end %>
      <div class="right_wrapper">
        <%= f.submit ' 登録', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
  

app/views/requests/_request_button.html.erb
<% if current_user.admin? && request.charge_user != current_user.id %>
  <%= link_to '担当する', request_path(request, charge_user_id: current_user.id ,status: "対応中"), method: :patch, class: 'btn btn-sm btn-primary' %>
<% elsif current_user.admin? %>
  <%= link_to '解除する', request_path(request, charge_user_id: '',status: "新規"), method: :patch, class: 'btn btn-sm btn-primary' %>
<% end %>

app/views/requests/edit.html.erb
<h1>依頼の編集</h1>


<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <%= render 'form', request: @request %>
  </div>
</div>


<%= link_to '詳細に戻る', request_path %>

app/views/requests/index.html.erb
<h1>■依頼一覧</h1>

<div class="container">
  
  <div　class="row col-xs-8"> 
    <div class="panel-group">
      <div class="panel panel-default">
        
        <div class="panel-heading">
          <h3 class="panel-title">
            <a data-toggle="collapse" data-parent="#sampleAccordion" href="#sampleAccordionCollapse1">
              検索条件
            </a>
          </h3>
        </div>

        <div class="panel-body">
          <%= form_tag requests_path, :method => 'get' do %> <%#　projects_pathはモデル名で読みかえること %>
              <%= label_tag :name, "タイトル" %>
              <%= text_field_tag :title, params[:title] %>
              <%= label_tag :name, "ステータス" %>
              <%= select_tag :status, options_for_select(Request.statuses, :selected => params[:status]), include_blank: true %>

              <%= submit_tag "検索", :name => nil %>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <div class="row col-xs-12"> 
  
  <table class="table table-striped">
    <tr class="success">
      <th>タイトル</th>
      <th>依頼者</th>
      <th>依頼者所属</th>
      <th>期日</th>
      <th>作成日</th>
      <th>ステータス</th>
      <th>MIT担当者</th>
      <th>詳細</th>
      <th>　</th>
  
    </tr>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.title %></td>
        <td><%= request.user.name %></td>
        <td><%= request.user.dept %></td>
        <td><%= request.limit_date %></td>
        <td><%= request.created_at %></td>
        <td><%= request.status %></td>
        <td><%= request.charge_user_name %> </td>
  
        <td><%= link_to '詳細', request , class: 'btn btn-sm btn-success'%></td>
        
        <td id="request-button-<%= request.id %>"><%= render 'requests/request_button', request: request if current_user.admin?%></td>
      </tr>
    <% end %>
  </table>
  
  </div>
</div>

app/views/requests/new.html.erb
<h1>IT依頼新規作成ページ</h1>


<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <%= render 'form', request: @request %>
  </div>
</div>


<%= link_to '一覧に戻る', root_path %>

app/views/requests/show.html.erb
<h2>■依頼詳細</h2>

<!--完了とするボタンは、管理者モードの場合のみ表示される-->
<% if current_user.admin? %>    
	  
  <div class="button_wrapper">
    <% if @request.persisted? %>
      <%= link_to ' 完了にする', request_path(request, id:@request.id ,charge_user_id: current_user.id ,status: "完了"), method: :patch, class: 'btn btn-lg btn-warning glyphicon glyphicon-flag' %>
    <% end %>
  </div>
  <br>
 <% end %>
  
  <div class="col-md-8 col-md-offset-2">

	<form class="form-horizontal" >
	
	  <div class="form-group">
	  	<label class="control-label" for="InputText">依頼者</label>
  		<input type="text" class="form-control" id="InputText" readonly="readonly" value=<%=  @user.name %>>
		</div>
	
	  <div class="form-group">
	  	<label class="control-label" for="InputText">タイトル</label>
  		<input type="text" class="form-control" id="InputText" readonly="readonly" value=<%= @request.title  %> >
		</div>
	
	  <div class="form-group">
	  	<label class="control-label" for="InputText">期日</label>
  		<input type="text" class="form-control" id="InputText" readonly="readonly" value=<%= @request.limit_date %> >
	  </div>
	
	  <div class="form-group">
	  	<label class="control-label" for="InputText">内容</label>
  		<textarea name="description" class="form-control" id="InputTextarea" readonly="readonly" rows="10"><%= @request.description %></textarea><br>
	  </div>
	
	  <div class="form-group">
	  	<label class="control-label" for="InputText">状況</label>
  		<input type="text" class="form-control" id="InputText" readonly="readonly" value=<%= @request.status %>>
		</div>

	  <div class="form-group">
	  	<label class="control-label" for="InputText">担当者</label>
  		<input type="text" class="form-control" id="InputText" readonly="readonly" value=<%= @request.charge_user_name %>  >
		</div>
	
	
	  <div class="form-group">
	  	<label class="control-label" for="InputText">回答内容</label>
  		<textarea name="message" class="form-control" id="InputTextarea" readonly="readonly" rows="10"><%= @request.message %></textarea><br>
		</div>
	</form>

	<!--編集・削除ボタンは、管理者モードの場合のみ表示される-->
  <div class="right_wrapper">
		<% if current_user.admin? %>    
			<%= link_to " edit", edit_request_path(@request), class: 'btn btn-primary glyphicon glyphicon-pencil'  %>
		    <%= link_to " delete", @request, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger glyphicon glyphicon-trash' %>
		<% end %>
  </div>

	<%= link_to '一覧に戻る', root_path %>

  </div>

</div>

app/views/requests/update.js.erb
$('#request-button-<%= @request.id %>').html("<%=j render 'requests/request_button', request: @request %>");

app/views/toppages/_index_task.html.erb
  <h3><font color="blue"><%= current_user.name %>さんに割当てられたタスクは <%= @tasks.count %>件あります </font></h3>
  
  <table class="table table-striped">
    <tr class="success">
      <th>タイトル</th>
      <th>依頼者</th>
      <th>メール</th>
      <th>部署</th>
      <th>期日</th>
      <th>作成日</th>
      <th>ステータス</th>
      <th>詳細</th>
      <th>編集</th>
  
    </tr>
    <% @tasks.each do |t| %>
      <tr>
        <td><%= t.title %></td>
        <td><%= t.user.name %></td>
        <td><%= t.user.email %></td>
        <td><%= t.user.dept %></td>
        <td><%= t.limit_date.strftime("%Y/%m/%d") %></td>
        <td><%= t.created_at.strftime("%Y/%m/%d %H:%M") %></td>
        <td><%= t.status %></td>

        <td><%= link_to '', t , class: 'btn btn-sm btn-success glyphicon glyphicon-list-alt'%></td>
        <td><%= link_to '', edit_request_path(t)  , class: 'btn btn-sm btn-primary glyphicon glyphicon-pencil'%></td>
        
      </tr>
    <% end %>
  </table>

app/views/toppages/index.html.erb
<% if logged_in? %>

  <p><%= current_user.role %> <%= current_user.name %>　さん</p>

   <div class="center jumbotron">
    <div class="button_wrapper">
      <%= link_to ' 新規に依頼する', new_request_path, class: 'btn btn-lg btn-primary glyphicon glyphicon-edit' %>
    </div>
  </div>

  <% if @requests.exists? %>

    <h3><%= current_user.name %>さんの依頼は <%= @requests.count %>件あります</h3>
    <table class="table table-striped">
      <tr class="warning">
        <th>タイトル</th>
        <th>内容</th>
        <th>期日</th>
        <th>作成日</th>
        <th>ステータス</th>
        <th>MIT担当者</th>
        <th>詳細</th>
      
      </tr>
      <% @requests.each do |request| %>
        <tr>
          <td><%= request.title %></td>
          <td><%= request.description %></td>
          <td><%= request.limit_date.strftime("%Y/%m/%d") %></td>
          <td><%= request.created_at.strftime("%Y/%m/%d %H:%M") %></td>
          <td><%= request.status %></td>
          <td><%= request.charge_user_name %> </td>
        
          <td><%= link_to '詳細', request , class: 'btn btn-sm btn-success '%></td>
          
        </tr>
      <% end %>
    </table>
  <% else %>
    <p>(<%= current_user.name %>さんの依頼はありません) </p>
  <% end %>
  
  <% if current_user.admin? %>
    <div>
      <%= render 'index_task', tasks: @tasks %>
    </div>
  <% end %>


<% else %>


 <% content_for :cover do %>
    <div class="cover">
      <div class="cover-inner">
        <div class="cover-contents">
          <h1>IT依頼へようこそ</h1>
        </div>
      </div>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(:session, url: login_path) do |f| %>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <%= f.submit 'Log in', class: 'btn btn-primary btn-block' %>
    <% end %>

    <p>New user? <%= link_to 'Sign up now!', signup_path %></p>
  </div>
</div>

<% end %>

app/views/users/_userform.html.erb
  <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
  
    <div class="form-group">
      <%= f.label :name, '氏名' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
  
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（確認用）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

    <div class="form-group">
      <%= f.label :base, '拠点' %>
      <%= f.text_field :base, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label :dept, '部署名' %>
      <%= f.text_field :dept, class: 'form-control' %>
    </div>
    
    <% if @user.persisted? %>
      <div class="form-group">
        <%= f.label :role, '権限' %>
        <%= f.select :role, User.roles.keys.to_a, {}, class: 'form-control' %>
      </div>
    <% else %>
      <%= f.hidden_field :role, :value => "一般" %>
    <% end %>

    <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
  <% end %>

app/views/users/edit.html.erb
<h2>■ユーザ編集</h2>

<%= form_for(@user) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="col-md-6 col-md-offset-3">
    <%= render 'userform', user: @user %>
  </div>
  
<% end %>

app/views/users/index.html.erb
<h1>■ユーザ一覧</h1>
<div class="container">
  
  <div　class="row col-xs-8"> 
    <div class="panel-group">
      <div class="panel panel-default">
        
        <div class="panel-heading">
          <h3 class="panel-title">
            <a data-toggle="collapse" data-parent="#sampleAccordion" href="#sampleAccordionCollapse1">
              検索条件
            </a>
          </h3>
        </div>

        <div class="panel-body">
          <%= form_tag(users_path, method: "get") do %>
            <%= label_tag :name, "名前" %><%= text_field_tag :name, params[:name] %>
            <%= label_tag :name, "権限" %>
            <%= select_tag :role, options_for_select(User.roles, :selected => params[:role]), include_blank: true %>
            <%= submit_tag "検索" %>
          <% end %>
        </div>
     </div>
    </div>
  </div>



<div> 

  <table class="table table-striped">
    <tr class="info">
      <th>名前</th>
      <th>メールアドレス</th>
      <th>拠点</th>
      <th>部門</th>
      <th>権限</th>
      <th>...</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name%></td>
        <td><%= user.email %></td>
        <td><%= user.base %></td>
        <td><%= user.dept %></td>
        <td><%= user.role %></td>
        <td><%= link_to '詳細', user , class: 'btn btn-sm btn-success '%></td>
      </tr>
    <% end %>
  </table>
  <%= link_to '新規ユーザ登録', signup_path %>

</div>

app/views/users/new.html.erb
<h1>ユーザ新規作成ページ</h1>


<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="col-md-6 col-md-offset-3">
  <%= render 'userform', user: @user %>
</div>



<%= link_to '一覧に戻る', users_path %>

app/views/users/show.html.erb
<h2>■ユーザ詳細ページ</h2>

<div class="col-md-8 col-md-offset-2">

   <form class="form-horizontal">

  	<div class="form-group">
  		<label class="control-label" for="InputText">ユーザID</label>
			<input type="number" class="form-control" id="InputNumber" value=<%=  @user.id %> readonly>
		</div>

  	<div class="form-group">
  		<label class="control-label" for="InputText">名前</label>
  			<input type="text" class="form-control" id="InputText" value=<%=  @user.name %> readonly>
 		</div>
 
  	<div class="form-group">
  		<label class="control-label" for="InputText">メールアドレス</label>
			<input type="text" class="form-control" id="InputText" value=<%= @user.email %> readonly>
		</div>

  	<div class="form-group">
  		<label class="control-label" for="InputText">拠点</label>
			<input type="text" class="form-control" id="InputText" value=<%= @user.base %> readonly>
		</div>

  	<div class="form-group">
  		<label class="control-label" for="InputText">部門</label>
			<input type="text" class="form-control" id="InputText" value=<%= @user.dept %> readonly>
		</div>

  	<div class="form-group">
  		<label class="control-label" for="InputText">権限</label>
			<input type="text" class="form-control" id="InputText" value=<%= @user.role %> readonly>
		</div>

  </form>

	<% if logged_in? %>
	  <div class="right_wrapper">
			<%= link_to " edit", edit_user_path(@user), class: 'btn btn-primary glyphicon glyphicon-pencil'  %>
			<% if current_user.id != @user.id %>	
				<%= link_to " delete", @user, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger glyphicon glyphicon-trash' %>
			<% end %>
		</div>
		<!--admin権限の場合のみ表示する-->
		<% if current_user.admin? %>
			<%= link_to '一覧に戻る', users_path %>
		<% end %>
	<% end %>
</div>